export const metadata = {
    title: "Terms of Service",
}

export default async function PrivacyPolicyPage() {
    return (
        <div>
            <div className="my-8">
                <div className="mx-auto  px-4 sm:px-6 lg:px-8">
                    <div className="text-center">
                        <p className="mt-1 flex w-full items-center justify-center gap-8 text-4xl font-bold tracking-tight text-brandtext-500 sm:text-5xl lg:text-6xl">
                            Terms of Service
                        </p>
                        <p className="mt-2">Last modified April 30th, 2023</p>
                    </div>
                </div>
            </div>
            <div className="prose prose-sm lg:-prose-lg mx-auto w-full max-w-4xl">
                <h2>Introduction</h2>
                <p>
                    Welcome to the Pixelfy application (the "Application"),
                    which uses artificial intelligence to generate pixel art
                    images. By using the Application, you agree to be bound by
                    these terms of service (the "Terms"). If you do not agree to
                    these Terms, you may not use the Application.
                </p>

                <h2>Use of the Application</h2>
                <p>
                    The Application is intended for personal and commercial use.
                    Users may purchase credits to generate images, and for each
                    successful generation a credit is used. Users may also use
                    the images they generate commercially without any
                    attribution required. However, the Application itself is
                    open source and must be attributed to its original creators.
                </p>

                <h2>Intellectual Property</h2>
                <p>
                    The Application and all of its contents, including but not
                    limited to text, graphics, images, and software, are the
                    property of the Application's owners and are protected by
                    applicable copyright and other intellectual property laws.
                    However, any images generated by users using the Application
                    ("User-Generated Images") are the property of the respective
                    users. The owners do not claim any ownership rights in
                    User-Generated Images. Users are free to use, modify, and
                    distribute their User-Generated Images for any purpose,
                    including commercial purposes, without any attribution or
                    compensation owed to the owners.
                </p>

                <h2>User Conduct</h2>
                <p>
                    You agree not to use the Application for any unlawful
                    purpose or in any way that could damage, disable,
                    overburden, or impair the Application. You also agree not to
                    interfere with the proper working of the Application or
                    attempt to bypass any security measures put in place by the
                    owners.
                </p>

                <h2>Disclaimer of Warranties</h2>
                <p>
                    The Application is provided "as is" and without warranty of
                    any kind. The owners make no warranties, express or implied,
                    including but not limited to warranties of merchantability
                    or fitness for a particular purpose, with respect to the
                    Application or its contents.
                </p>

                <h2>Limitation of Liability</h2>
                <p>
                    The owners shall not be liable for any direct, indirect,
                    incidental, consequential, or punitive damages arising out
                    of or in connection with the use of the Application. This
                    includes, but is not limited to, any errors or omissions in
                    the content of the Application, or any loss or damage of any
                    kind arising from or in connection with the use of the
                    Application.
                </p>

                <h2>Indemnification</h2>
                <p>
                    You agree to indemnify and hold harmless the owners, their
                    affiliates, and their respective officers, directors,
                    employees, and agents, from any claim or demand, including
                    reasonable attorneys' fees, made by any third party due to
                    or arising out of your use of the Application, your
                    violation of these Terms, or your violation of any rights of
                    another.
                </p>

                <h2>Changes to these Terms</h2>
                <p>
                    The owners reserve the right to modify these Terms at any
                    time, without prior notice to you. Your continued use of the
                    Application after such modifications constitutes your
                    acceptance of the modified Terms.
                </p>

                <h2>Termination</h2>
                <p>
                    The owners may terminate your access to the Application at
                    any time, without prior notice, for any reason, including
                    but not limited to your violation of these Terms or any
                    applicable law.
                </p>

                <h2>Governing Law</h2>
                <p>
                    These Terms and any dispute arising out of or in connection
                    with these Terms shall be governed by and construed in
                    accordance with the laws of the jurisdiction in which the
                    owners are located. Any legal action or proceeding arising
                    out of or relating to these Terms shall be brought in the
                    courts of that jurisdiction, and you hereby consent to the
                    exclusive jurisdiction and venue of those courts.
                </p>
            </div>
        </div>
    )
}
