import { DashboardShell } from "@/components/shell"
import { db } from "@/lib/db"
import type { Metadata } from "next"
import Image from "next/image"

type Props = {
    params: { id: string }
    searchParams: { [key: string]: string | string[] | undefined }
}

export async function generateMetadata({
    params: { id: photoId },
}: Props): Promise<Metadata> {
    const photo = await db.outputImage.findUniqueOrThrow({
        where: {
            id: photoId,
        },
        include: {
            generation: true,
        },
    })

    return {
        title: "Check out my pixel art generated by AI",
        description: photo?.generation.prompt,
        openGraph: {
            title: "Check out my pixel art generated by AI",
            description: photo?.generation.prompt,
            images: [photo?.pixelatedImage ?? ""],
        },
        twitter: {
            card: "summary_large_image",
            title: "Check out my pixel art generated by AI",
            description: photo?.generation.prompt,
            images: [photo?.pixelatedImage ?? ""],
            creator: "@dparksdev",
        },
    }
}

export default async function GenerationModal({ params: { id: imageId } }) {
    const image = await db.outputImage.findUnique({
        where: {
            id: imageId,
        },
        include: {
            generation: {
                include: {
                    user: true,
                },
            },
        },
    })
    return (
        <DashboardShell>
            <div className="container mx-auto w-full flex flex-col items-center justify-center dark:bg-transparent mt-8">
                {image && (
                    <div>
                        <Image
                            height={512}
                            width={512}
                            alt={image?.generation.prompt}
                            src={image?.pixelatedImage}
                        />
                    </div>
                )}
                <div className="mx-auto flex w-full flex-col gap-4 md:max-w-[58rem] text-center mt-8 pb-24">
                    <h2 className="font-heading text-3xl leading-[1.1] sm:text-3xl md:text-5xl">
                        {image?.generation.prompt}
                    </h2>
                </div>
            </div>
        </DashboardShell>
    )
}
