// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Guide = Collections['guides']['schema']['_output']
export declare const guides: Guide[]

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]
